name: 'Smurf'
description: 'Builds, tags, scans, pushes, and removes Docker images using the Smurf CLI'

inputs:
  tool:
    description: 'Tool to use'
    required: true
  command:
    description: 'Command to run'
    required: true
  SUBSCRIPTION_ID:
    description: 'Azure Subscription ID'
    required: false
  RESOURCE_GROUP:
    description: 'Azure Resource Group'
    required: false
  REGISTRY_NAME:
    description: 'Registry Name'
    required: false
  REGION:
    description: 'Region'
    required: false
  PROJECT_ID:
    description: 'GCP Project ID'
    required: false
  REPOSITORY:
    description: 'Repository'
    required: false
  IMAGE_NAME:
    description: 'Docker Image Name'
    required: false
  IMAGE_TAG:
    description: 'Docker Image Tag'
    required: false
  DELETE_AFTER_PUSH:
    description: 'Delete image after push (true or false)'
    required: false
    default: 'false'
  SOURCE_TAG:
    description: 'Source image and tag for tagging'
    required: false
  TARGET_TAG:
    description: 'Target repository/image and tag for tagging'
    required: false
  SARIF_OUTPUT:
    description: 'Output file for image scan results'
    required: false
  DOCKERFILE_PATH:
    description: 'Path to the Dockerfile'
    required: false
    default: './Dockerfile'
  DOCKER_USERNAME:
    description: 'Docker Hub username'
    required: false
  DOCKER_PASSWORD:
    description: 'Docker Hub password'
    required: false
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SUBSCRIPTION_ID: ${{ inputs.SUBSCRIPTION_ID }}
    RESOURCE_GROUP: ${{ inputs.RESOURCE_GROUP }}
    REGISTRY_NAME: ${{ inputs.REGISTRY_NAME }}
    REGION: ${{ inputs.REGION }}
    PROJECT_ID: ${{ inputs.PROJECT_ID }}
    REPOSITORY: ${{ inputs.REPOSITORY }}
    IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
    IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
    DELETE_AFTER_PUSH: ${{ inputs.DELETE_AFTER_PUSH }}
    SOURCE_TAG: ${{ inputs.SOURCE_TAG }}
    TARGET_TAG: ${{ inputs.TARGET_TAG }}
    SARIF_OUTPUT: ${{ inputs.SARIF_OUTPUT }}
    DOCKERFILE_PATH: ${{ inputs.DOCKERFILE_PATH }}
    DOCKER_USERNAME: ${{ inputs.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ inputs.DOCKER_PASSWORD }}
  args:
    - ${{ inputs.tool }}
    - ${{ inputs.command }}
    - ${{ inputs.IMAGE_NAME }}
    - ${{ inputs.IMAGE_TAG }}
    # - ${{ inputs.SUBSCRIPTION_ID }}
    # - ${{ inputs.RESOURCE_GROUP }}
    # - ${{ inputs.REGION }}
    # - ${{ inputs.REGISTRY_NAME }}
    # - ${{ inputs.REPOSITORY }}
    # - ${{ inputs.DELETE_AFTER_PUSH }}
    # - ${{ inputs.SOURCE_TAG }}
    # - ${{ inputs.TARGET_TAG }}
    # - ${{ inputs.SARIF_OUTPUT }}
    # - ${{ inputs.DOCKERFILE_PATH }}
