name: Reusable Smurf Workflow

on:
  workflow_call:
    inputs:
      tool:
        description: "Specify the tool to use, e.g., sdkr"
        required: true
        type: string
      command:
        description: "Specify the command to execute, e.g., build, push, scan"
        required: true
        type: string
      args:
        description: "Arguments for the smurf command"
        required: false
        type: string

jobs:
  smurf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build Smurf CLI
        run: |
          go build -o smruf

      - name: Run Smurf Command
        run: |
          chmod +x ./smruf
          ./smruf ${{ inputs.tool }} ${{ inputs.command }} ${{ inputs.args }}
